/*
 Artica CC - http://artica.cc

 Gyro Bumper V0.1 - Serras and Tarquinio

 This Software is under The MIT License (MIT)

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 */


#ifndef _BUMPERPROTOCOL_H_
#define _BUMPERPROTOCOL_H_

// --------------------------------------------------------------------------------
// PROTOCOL Commands Received - I2C/TWI - Interrupt Managed (decoded on Parser function)
enum _ReceivedOrderBumper {
	RX_NONE,				// DEFAULT....
	CFG,						// CONFIG ALL

	GLGESTURE,
	GLRED,
	GLGREEN,
	GLBLUE,
	GLAMBIENT,
	GLPROXIMITY,
	GLLINE,
	SLLED,

	GRGESTURE,
	GRRED,
	GRGREEN,
	GRBLUE,
	GRAMBIENT,
	GRPROXIMITY,
	GRLINE,
	SRLED,

	GCGESTURE,
	GCRED,
	GCGREEN,
	GCBLUE,
	GCAMBIENT,
	GCPROXIMITY,
	SCLED,

	SRGB						// Set RGB Value
};

// --------------------------------------------------------------------------------
// Update States for "later" reply (to do not block the Wire Interrupt for too much time)
enum _ProcessLaterOrdersBumper {
	NO_RX, REPLY_CFG,						// CONFIG ALL
REPLY_GLRED,
REPLY_GLGREEN,
REPLY_GLBLUE,
REPLY_GLAMBIENT,
REPLY_GLPROXIMITY,
REPLY_GLGESTURE,
REPLY_GLLINE,
REPLY_SLLED,
REPLY_GRRED,
REPLY_GRGREEN,
REPLY_GRBLUE,
REPLY_GRAMBIENT,
REPLY_GRPROXIMITY,
REPLY_GRGESTURE,
REPLY_GRLINE,
REPLY_SRLED,
REPLY_GCRED,
REPLY_GCGREEN,
REPLY_GCBLUE,
REPLY_GCAMBIENT,
REPLY_GCPROXIMITY,
REPLY_GCGESTURE,
REPLY_SCLED,
REPLY_SRGB

};

enum _BumperConfig {
	SENSOR_OFF,	SENSOR_PROXIMITY, SENSOR_GESTURE, SENSOR_RGB
};

enum _GestureState {
	UP, DOWN, LEFT, RIGHT, NEAR, FAR, NONE
};

#endif /* _BUMPERPROTOCOL_H_ */
